name = "zhizhi-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"
account_id = "cbc61c73bf26f3a3c2d61d6a26846765"

# 环境变量（部署时在Cloudflare Dashboard设置）
[vars]
# API_KEY = "your-api-key"

# 开发环境
[env.dev]
vars = { ENVIRONMENT = "development" }

# 生产环境
[env.production]
vars = { ENVIRONMENT = "production" }
