// 简单的拼音转换（只包含常用字）
const pinyinMap: { [key: string]: string } = {
  '啊': 'a', '阿': 'a', '哎': 'ai', '爱': 'ai', '安': 'an', '按': 'an',
  '八': 'ba', '吧': 'ba', '白': 'bai', '百': 'bai', '班': 'ban', '板': 'ban',
  '北': 'bei', '本': 'ben', '比': 'bi', '笔': 'bi', '边': 'bian', '别': 'bie',
  '冰': 'bing', '不': 'bu', '步': 'bu',
  '才': 'cai', '菜': 'cai', '草': 'cao', '曾': 'ceng', '茶': 'cha', '长': 'chang',
  '朝': 'chao', '车': 'che', '陈': 'chen', '成': 'cheng', '吃': 'chi', '出': 'chu',
  '川': 'chuan', '春': 'chun', '次': 'ci', '从': 'cong', '村': 'cun',
  '大': 'da', '带': 'dai', '单': 'dan', '当': 'dang', '到': 'dao', '的': 'de',
  '灯': 'deng', '地': 'di', '点': 'dian', '电': 'dian', '丁': 'ding', '东': 'dong',
  '都': 'dou', '读': 'du', '度': 'du', '对': 'dui', '多': 'duo',
  '儿': 'er', '二': 'er',
  '发': 'fa', '法': 'fa', '反': 'fan', '方': 'fang', '房': 'fang', '飞': 'fei',
  '分': 'fen', '风': 'feng', '服': 'fu', '福': 'fu',
  '该': 'gai', '干': 'gan', '感': 'gan', '刚': 'gang', '高': 'gao', '哥': 'ge',
  '个': 'ge', '给': 'gei', '跟': 'gen', '更': 'geng', '工': 'gong', '公': 'gong',
  '狗': 'gou', '姑': 'gu', '古': 'gu', '瓜': 'gua', '关': 'guan', '光': 'guang',
  '贵': 'gui', '国': 'guo', '果': 'guo',
  '还': 'hai', '海': 'hai', '汉': 'han', '好': 'hao', '号': 'hao', '和': 'he',
  '河': 'he', '黑': 'hei', '很': 'hen', '红': 'hong', '后': 'hou', '呼': 'hu',
  '胡': 'hu', '花': 'hua', '话': 'hua', '画': 'hua', '怀': 'huai', '欢': 'huan',
  '黄': 'huang', '回': 'hui', '会': 'hui', '火': 'huo', '或': 'huo',
  '机': 'ji', '鸡': 'ji', '几': 'ji', '己': 'ji', '记': 'ji', '家': 'jia',
  '间': 'jian', '见': 'jian', '江': 'jiang', '讲': 'jiang', '叫': 'jiao', '教': 'jiao',
  '街': 'jie', '姐': 'jie', '今': 'jin', '金': 'jin', '进': 'jin', '京': 'jing',
  '经': 'jing', '就': 'jiu', '九': 'jiu', '酒': 'jiu', '句': 'ju', '觉': 'jue',
  '开': 'kai', '看': 'kan', '可': 'ke', '课': 'ke', '空': 'kong', '口': 'kou',
  '哭': 'ku', '快': 'kuai', '块': 'kuai',
  '来': 'lai', '老': 'lao', '了': 'le', '乐': 'le', '李': 'li', '里': 'li',
  '理': 'li', '力': 'li', '连': 'lian', '脸': 'lian', '两': 'liang', '亮': 'liang',
  '林': 'lin', '零': 'ling', '六': 'liu', '刘': 'liu', '龙': 'long', '楼': 'lou',
  '路': 'lu', '旅': 'lv', '绿': 'lv',
  '妈': 'ma', '马': 'ma', '吗': 'ma', '买': 'mai', '卖': 'mai', '慢': 'man',
  '忙': 'mang', '猫': 'mao', '没': 'mei', '美': 'mei', '妹': 'mei', '们': 'men',
  '米': 'mi', '面': 'mian', '民': 'min', '明': 'ming', '名': 'ming', '木': 'mu',
  '那': 'na', '哪': 'na', '南': 'nan', '难': 'nan', '呢': 'ne', '内': 'nei',
  '能': 'neng', '你': 'ni', '年': 'nian', '鸟': 'niao', '您': 'nin', '牛': 'niu',
  '女': 'nv',
  '哦': 'o', '欧': 'ou',
  '怕': 'pa', '拍': 'pai', '盘': 'pan', '旁': 'pang', '朋': 'peng', '皮': 'pi',
  '片': 'pian', '票': 'piao', '平': 'ping', '苹': 'ping', '破': 'po',
  '七': 'qi', '其': 'qi', '起': 'qi', '气': 'qi', '千': 'qian', '前': 'qian',
  '钱': 'qian', '强': 'qiang', '桥': 'qiao', '切': 'qie', '亲': 'qin', '青': 'qing',
  '轻': 'qing', '清': 'qing', '情': 'qing', '请': 'qing', '秋': 'qiu', '去': 'qu',
  '全': 'quan', '让': 'rang', '热': 're', '人': 'ren', '认': 'ren', '日': 'ri',
  '容': 'rong', '如': 'ru', '入': 'ru',
  '三': 'san', '色': 'se', '山': 'shan', '商': 'shang', '上': 'shang', '少': 'shao',
  '谁': 'shei', '身': 'shen', '什': 'shen', '生': 'sheng', '声': 'sheng', '师': 'shi',
  '十': 'shi', '时': 'shi', '实': 'shi', '食': 'shi', '是': 'shi', '事': 'shi',
  '室': 'shi', '手': 'shou', '书': 'shu', '树': 'shu', '水': 'shui', '睡': 'shui',
  '说': 'shuo', '四': 'si', '送': 'song', '苏': 'su', '虽': 'sui', '孙': 'sun',
  '所': 'suo',
  '他': 'ta', '她': 'ta', '它': 'ta', '太': 'tai', '汤': 'tang', '糖': 'tang',
  '特': 'te', '天': 'tian', '田': 'tian', '条': 'tiao', '跳': 'tiao', '听': 'ting',
  '同': 'tong', '头': 'tou', '图': 'tu', '土': 'tu', '腿': 'tui',
  '外': 'wai', '玩': 'wan', '晚': 'wan', '万': 'wan', '王': 'wang', '往': 'wang',
  '为': 'wei', '位': 'wei', '文': 'wen', '问': 'wen', '我': 'wo', '五': 'wu',
  '午': 'wu', '物': 'wu',
  '西': 'xi', '希': 'xi', '习': 'xi', '喜': 'xi', '洗': 'xi', '系': 'xi',
  '下': 'xia', '先': 'xian', '现': 'xian', '想': 'xiang', '向': 'xiang', '小': 'xiao',
  '笑': 'xiao', '些': 'xie', '写': 'xie', '谢': 'xie', '新': 'xin', '心': 'xin',
  '信': 'xin', '星': 'xing', '行': 'xing', '姓': 'xing', '兴': 'xing', '雄': 'xiong',
  '休': 'xiu', '学': 'xue', '雪': 'xue',
  '呀': 'ya', '眼': 'yan', '羊': 'yang', '样': 'yang', '要': 'yao', '也': 'ye',
  '夜': 'ye', '一': 'yi', '衣': 'yi', '医': 'yi', '已': 'yi', '以': 'yi',
  '意': 'yi', '因': 'yin', '音': 'yin', '银': 'yin', '应': 'ying', '英': 'ying',
  '用': 'yong', '有': 'you', '友': 'you', '又': 'you', '右': 'you', '鱼': 'yu',
  '雨': 'yu', '语': 'yu', '远': 'yuan', '院': 'yuan', '月': 'yue', '云': 'yun',
  '在': 'zai', '再': 'zai', '早': 'zao', '怎': 'zen', '张': 'zhang',
  '赵': 'zhao', '找': 'zhao', '这': 'zhe', '着': 'zhe', '真': 'zhen', '正': 'zheng',
  '之': 'zhi', '知': 'zhi', '只': 'zhi', '中': 'zhong', '钟': 'zhong', '种': 'zhong',
  '重': 'zhong', '周': 'zhou', '主': 'zhu', '住': 'zhu', '祝': 'zhu', '专': 'zhuan',
  '准': 'zhun', '桌': 'zhuo', '子': 'zi', '字': 'zi', '自': 'zi', '走': 'zou',
  '最': 'zui', '昨': 'zuo', '左': 'zuo', '坐': 'zuo', '做': 'zuo', '作': 'zuo',
}

export const toPinyin = (str: string): string => {
  return str
    .split('')
    .map(char => pinyinMap[char] || char.toLowerCase())
    .join('')
    .replace(/[^a-z0-9]/g, '')
}

