// 谁是卧底词库
export const wordPairs = [
  { civilian: '牛奶', undercover: '豆浆' },
  { civilian: '包子', undercover: '饺子' },
  { civilian: '眉毛', undercover: '睫毛' },
  { civilian: '状元', undercover: '冠军' },
  { civilian: '饺子', undercover: '包子' },
  { civilian: '摩托车', undercover: '电动车' },
  { civilian: '高跟鞋', undercover: '增高鞋' },
  { civilian: '汉堡', undercover: '肉夹馍' },
  { civilian: '薰衣草', undercover: '满天星' },
  { civilian: '金庸', undercover: '古龙' },
  { civilian: '保安', undercover: '保镖' },
  { civilian: '白菜', undercover: '生菜' },
  { civilian: '辣椒', undercover: '芥末' },
  { civilian: '赵敏', undercover: '黄蓉' },
  { civilian: '海豚', undercover: '海狮' },
  { civilian: '周杰伦', undercover: '陈奕迅' },
  { civilian: '麻雀', undercover: '乌鸦' },
  { civilian: '橙子', undercover: '橘子' },
  { civilian: '葫芦娃', undercover: '奥特曼' },
  { civilian: '玫瑰', undercover: '月季' },
  { civilian: '西瓜', undercover: '哈密瓜' },
  { civilian: '苹果', undercover: '梨' },
  { civilian: '香蕉', undercover: '芭蕉' },
  { civilian: '葡萄', undercover: '提子' },
  { civilian: '草莓', undercover: '樱桃' },
  { civilian: '柠檬', undercover: '柚子' },
  { civilian: '桃子', undercover: '杏子' },
  { civilian: '芒果', undercover: '木瓜' },
  { civilian: '菠萝', undercover: '凤梨' },
  { civilian: '火龙果', undercover: '猕猴桃' },
  { civilian: '馒头', undercover: '花卷' },
  { civilian: '面条', undercover: '米线' },
  { civilian: '米饭', undercover: '粥' },
  { civilian: '炒饭', undercover: '盖浇饭' },
  { civilian: '煎饼', undercover: '烙饼' },
  { civilian: '油条', undercover: '麻花' },
  { civilian: '豆腐', undercover: '豆干' },
  { civilian: '鸡蛋', undercover: '鸭蛋' },
  { civilian: '猪肉', undercover: '牛肉' },
  { civilian: '鸡肉', undercover: '鸭肉' },
  { civilian: '咖啡', undercover: '奶茶' },
  { civilian: '可乐', undercover: '雪碧' },
  { civilian: '绿茶', undercover: '红茶' },
  { civilian: '酸奶', undercover: '牛奶' },
  { civilian: '果汁', undercover: '饮料' },
  { civilian: '医生', undercover: '护士' },
  { civilian: '老师', undercover: '教授' },
  { civilian: '警察', undercover: '保安' },
  { civilian: '律师', undercover: '法官' },
  { civilian: '演员', undercover: '歌手' }
]

export function getRandomWordPair() {
  return wordPairs[Math.floor(Math.random() * wordPairs.length)]
}
